# NOTES:
# * When you first create a Netlify project, you should install the Netlify CLI (https://docs.netlify.com/cli/get-started/).
  # * Then, in a terminal, log into Netlify from inside your project directory by running `netlify login`.
  # * Then you should link your project to your Netlify account with `netlify link`.

# * In the Netlify UI, when you click "New site from Git" you will be prompted to set a "Build command" and a "Publish directory". This is what you should do:
  # Build command: #
  # Publish directory: (Leave this blank)
# * You can also set these by going to "Settings" > "Build & deploy" > "Continuous Deployment" > "Build settings".


[dev]
  functions = "functions" # You need to specify the folder where your functions will be served from during development otherwise the production functions will be served by default and they will have NODE_ENV = "production", which will mix up your dev and prod environments.
  # NODE_ENV = "development" # This has not been working for me, so I specified this in the npm 'dev' script.

[build]
  # The "base" setting is not necessary if your base directory is the root directory.
  # base = "/"
  functions = "functions" # This is the folder that holds your serverless functions. When you build your functions, Netlify will zip each of those functions and store the output zipped files inside the "/.netlify/functions" directory.
  # NODE_ENV = "production" # This didn't work for the [dev] block, so I am not specifying it here either.

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
